#ifdef __cplusplus
#pragma once
#endif

// DO NOT MODIFY THIS
#define WORLD_CHUNK_SIZE (16)

#define WORLD_CHUNK_NX (WORLD_CHUNK_SIZE)
#define WORLD_CHUNK_NY (WORLD_CHUNK_SIZE)
#define WORLD_CHUNK_NZ (WORLD_CHUNK_SIZE)
#define WORLD_CHUNK_NVOX (WORLD_CHUNK_NX*WORLD_CHUNK_NY*WORLD_CHUNK_NZ)

#define RENDER_DISTANCE (4) // x z
#define RENDER_HEIGHT (64/WORLD_CHUNK_NY)
#define WORLD_NCHUNKS (RENDER_DISTANCE*RENDER_DISTANCE*RENDER_HEIGHT)

//** GENERATION **//

#define CHUNK_GENERATION_LOCAL_SIZE_NX (8)
#define CHUNK_GENERATION_LOCAL_SIZE_NY (8)
#define CHUNK_GENERATION_LOCAL_SIZE_NZ (8)
#define CHUNK_GENERATION_LOCAL_SIZE_INVOCATIONS (CHUNK_GENERATION_LOCAL_SIZE_NX*CHUNK_GENERATION_LOCAL_SIZE_NY*CHUNK_GENERATION_LOCAL_SIZE_NZ)

#define CHUNK_GENERATION_WORKGROUP_NX (WORLD_CHUNK_NX/CHUNK_GENERATION_LOCAL_SIZE_NX)
#define CHUNK_GENERATION_WORKGROUP_NY (WORLD_CHUNK_NY/CHUNK_GENERATION_LOCAL_SIZE_NY)
#define CHUNK_GENERATION_WORKGROUP_NZ (WORLD_CHUNK_NZ/CHUNK_GENERATION_LOCAL_SIZE_NZ)
#define CHUNK_GENERATION_WORKGROUP_INVOCATIONS (CHUNK_GENERATION_WORKGROUP_NX*CHUNK_GENERATION_WORKGROUP_NY*CHUNK_GENERATION_WORKGROUP_NZ)

#define CHUNK_GENERATION_DISPATCH_INVOCATIONS (CHUNK_GENERATION_WORKGROUP_INVOCATIONS*CHUNK_GENERATION_LOCAL_SIZE_INVOCATIONS)

//** MESHING **//

#define CHUNK_MESHING_LOCAL_SIZE_NX (8)
#define CHUNK_MESHING_LOCAL_SIZE_NY (8)
#define CHUNK_MESHING_LOCAL_SIZE_NZ (8)
#define CHUNK_MESHING_LOCAL_SIZE_INVOCATIONS (CHUNK_MESHING_LOCAL_SIZE_NX*CHUNK_MESHING_LOCAL_SIZE_NY*CHUNK_MESHING_LOCAL_SIZE_NZ)

#define CHUNK_MESHING_WORKGROUP_NX (WORLD_CHUNK_NX/CHUNK_MESHING_LOCAL_SIZE_NX)
#define CHUNK_MESHING_WORKGROUP_NY (WORLD_CHUNK_NY/CHUNK_MESHING_LOCAL_SIZE_NY)
#define CHUNK_MESHING_WORKGROUP_NZ (WORLD_CHUNK_NZ/CHUNK_MESHING_LOCAL_SIZE_NZ)
#define CHUNK_MESHING_WORKGROUP_INVOCATIONS (CHUNK_MESHING_WORKGROUP_NX*CHUNK_MESHING_WORKGROUP_NY*CHUNK_MESHING_WORKGROUP_NZ)

#define CHUNK_MESHING_DISPATCH_INVOCATIONS (CHUNK_MESHING_WORKGROUP_INVOCATIONS*CHUNK_MESHING_LOCAL_SIZE_INVOCATIONS)

#if defined(__cplusplus)
static_assert(CHUNK_GENERATION_LOCAL_SIZE_INVOCATIONS <= 1024);
static_assert(CHUNK_MESHING_LOCAL_SIZE_INVOCATIONS <= 1024);
#endif